# Generated by Django 3.2.5 on 2021-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
