# Generated by Django 3.2.5 on 2021-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210714_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.CharField(default='', max_length=8, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(default='', max_length=500, verbose_name='Имя')),
                ('lastame', models.CharField(default='', max_length=500, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
