# Generated by Django 3.2.5 on 2021-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210714_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='password',
            field=models.CharField(default='', max_length=20, verbose_name='пароль1'),
        ),
    ]
