# Generated by Django 3.2.5 on 2021-07-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_people_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='lastame',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='username',
        ),
    ]
