# Generated by Django 3.2.5 on 2021-07-17 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
