# Generated by Django 3.2.5 on 2021-07-17 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('52521d53-8304-4a7b-85e3-3eb84212dc91'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
