# Generated by Django 3.2.5 on 2021-07-18 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('45d19eb3-00cf-40a6-b902-0ab7bd85a0e0'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
