# Generated by Django 3.2.5 on 2021-07-18 14:17

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='invalid email')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('d94ad91d-5a82-4e10-a851-4f9b5889b72c'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
