# Generated by Django 3.2.5 on 2021-07-19 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210718_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('6aed2dae-01ec-4008-92c9-d813172cce23'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
