# Generated by Django 3.2.5 on 2021-07-19 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('1f698777-bf33-4c81-9013-d778854e1756'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
