# Generated by Django 3.2.5 on 2021-07-21 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('92b08bfb-5f53-4057-9e3d-e31e491f829c'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
