# Generated by Django 3.2.5 on 2021-07-21 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('b6ef3622-63c9-437c-89af-a96ecf5546ce'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
