# Generated by Django 3.2.5 on 2021-07-21 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_people_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('244b52c2-6b40-48cc-9ff0-d964556cc28e'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
