# Generated by Django 3.2.5 on 2021-07-23 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210723_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='products',
            new_name='peopleform',
        ),
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('ca41d36a-18be-4f4c-95fa-7c963d91bf6f'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
