# Generated by Django 3.2.5 on 2021-07-23 06:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210723_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('71d59fce-ef61-4475-b37b-d12c3b766679'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
