# Generated by Django 3.2.5 on 2021-07-23 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('32539291-656e-460e-bfd4-84491ba19f56'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peopleprofile',
            name='butt',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, verbose_name='Кнопка'),
        ),
    ]
