# Generated by Django 3.2.5 on 2021-07-23 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210723_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('416045d7-e343-443d-9110-1d7f332fa83c'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peopleprofile',
            name='butt',
            field=models.IntegerField(choices=[('yes', 'Yes'), ('no', 'No')], verbose_name='Кнопка'),
        ),
    ]
