# Generated by Django 3.2.5 on 2021-07-23 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210723_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('4b60929b-396c-4c89-8f08-e466a5a137f4'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peopleprofile',
            name='butt',
            field=models.IntegerField(verbose_name='Кнопка'),
        ),
    ]
