# Generated by Django 3.2.5 on 2021-07-23 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210723_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('da762175-893a-4b03-825d-3af8c733f4a8'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='peopleform',
        ),
        migrations.AddField(
            model_name='profile',
            name='peopleform',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.peopleprofile'),
        ),
    ]
