# Generated by Django 3.2.5 on 2021-07-23 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0032_auto_20210723_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('8531347b-2f84-4a04-a0fe-2ac6f309c6d4'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='peopleform',
        ),
        migrations.AddField(
            model_name='profile',
            name='peopleform',
            field=models.ManyToManyField(to='main.PeopleProfile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
