# Generated by Django 3.2.5 on 2021-07-23 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('1b05c077-c17c-4150-9bee-81182eaa3f43'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
