# Generated by Django 3.2.5 on 2021-07-23 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(default=uuid.UUID('bec43882-73da-4c7e-a695-93060f3d2aef'), editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
